/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.services.Greeter;
import org.example.services.NameGreeter;
import org.example.services.RoleGreeter;

public class App {

    

    public static void main(String[] args) {
        String name = null;
        if (args.length == 1) {
            name = args[0];
        }
        // name = (args.length == 1) ? args[0]: null;
        //Greeter service = new NameGreeter();
        Greeter service = new RoleGreeter();
        System.out.println(service.getGreeting(name));
        if (service instanceof RoleGreeter) {
            RoleGreeter roleGreeter = (RoleGreeter) service;
            roleGreeter.calculateSalery(name);
        }
    }
}
